-- 코드를 입력하세요
SELECT ROUND(AVG(DAILY_FEE)) AS AVERAGE_FEE
from CAR_RENTAL_COMPANY_CAR where CAR_TYPE='SUV'

# SELECT ROUND(AVG(DAILY_FEE)) AS AVERAGE_FEE
# FROM CAR_RENTAL_COMPANY_CAR
# WHERE CAR_TYPE LIKE 'SUV'