SELECT T_H.HISTORY_ID, ROUND(T_H.DAILY_FEE * (1-IFNULL(P.DISCOUNT_RATE, 0)/100) * T_H.DURATION) AS FEE
FROM(
    # '트럭'의 대여 기록 정보
    SELECT H.HISTORY_ID, H.CAR_ID, H.START_DATE, H.END_DATE, DATEDIFF(H.END_DATE, H.START_DATE)+1 AS DURATION,
       C.CAR_TYPE, C.DAILY_FEE,
       CASE WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 7 THEN '7일 이상'
            ELSE NULL
            END AS 'DURATION_TYPE'
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    LEFT JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
) AS T_H
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON (T_H.DURATION_TYPE = P.DURATION_TYPE) AND (T_H.CAR_TYPE = P.CAR_TYPE)
ORDER BY FEE DESC, HISTORY_ID DESC